services:
  _defaults:
    autowire: true
    autoconfigure: true

  TimbleOne\BackendBundle\:
    resource: '../src/'

  TimbleOne\BackendBundle\OpenApi\JwtDecorator:
    decorates: 'lexik_jwt_authentication.api_platform.openapi.factory'
    arguments: [ '@TimbleOne\BackendBundle\OpenApi\JwtDecorator.inner' ]
